# Generated by scripts/update-formula.sh on release — do not edit by hand.
class Karya < Formula
  desc "AI-first, terminal-based IDE shipped as a single Go binary"
  homepage "https://github.com/drjzlyan/karya"
  version "0.4.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/drjzlyan/karya/releases/download/v0.4.3/karya_0.4.3_darwin_arm64.tar.gz"
      sha256 "069ef54d0cf28715cfd11d5e5a27c51cbecafb2dc5f49e7cfc394bc6efb22742"
    end
    on_intel do
      url "https://github.com/drjzlyan/karya/releases/download/v0.4.3/karya_0.4.3_darwin_amd64.tar.gz"
      sha256 "5c689cc7dd60fcc6cb77b74b6a0f31e063bf3d1c1897e0ac0b829dbffe0b2b6c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/drjzlyan/karya/releases/download/v0.4.3/karya_0.4.3_linux_arm64.tar.gz"
      sha256 "eda44a0b918c91e2395beabb4a310ed950872bf5c0c383dd756d36f23ca92f49"
    end
    on_intel do
      url "https://github.com/drjzlyan/karya/releases/download/v0.4.3/karya_0.4.3_linux_amd64.tar.gz"
      sha256 "6ad02aab5860ce2edaadabcd9c3765b450f691f6dfacbff02f2c3b05660e5d3c"
    end
  end

  def install
    bin.install "karya"
  end

  test do
    system "#{bin}/karya", "--version"
  end
end
