package cli

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/drjzlyan/karya/internal/ship"
	"github.com/drjzlyan/karya/internal/task"
)

// cmdInit implements `karya init`: it scaffolds a repository for the task
// workflow — .karya/ (task store + gitignore that keeps runtime state local)
// and a repo AGENTS.md generated from the detected toolchains, because agent
// quality is capped by context quality (DESIGN.md §10). Idempotent: existing
// files are never overwritten unless --force is given.
func cmdInit(args []string) int {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	force := fs.Bool("force", false, "overwrite an existing AGENTS.md")
	if err := fs.Parse(args); err != nil {
		return 2
	}

	// init writes only into the user's repo (.karya/, AGENTS.md), so it needs
	// no karya-owned dirs or managed env — unlike session commands it skips
	// newApp entirely.
	dir, _ := os.Getwd()
	top, err := ship.ExecRunner{}.Output(dir, "git", "rev-parse", "--show-toplevel")
	if err != nil {
		return fail(fmt.Errorf("karya init must run inside a git repository: %w", err))
	}
	top = strings.TrimSpace(top)

	if err := task.EnsureProjectDir(top); err != nil {
		return fail(err)
	}
	fmt.Printf("Scaffolded %s\n", task.ProjectDir(top))

	agentsPath := filepath.Join(top, "AGENTS.md")
	if _, err := os.Stat(agentsPath); err == nil && !*force {
		fmt.Println("AGENTS.md already exists (use --force to regenerate)")
		return 0
	}
	toolchains := detectToolchains(top)
	if err := os.WriteFile(agentsPath, []byte(renderAgentsMD(filepath.Base(top), toolchains)), 0o644); err != nil {
		return fail(fmt.Errorf("write AGENTS.md: %w", err))
	}
	if len(toolchains) == 0 {
		fmt.Println("Wrote AGENTS.md (no known toolchain detected; fill in the commands)")
	} else {
		names := make([]string, len(toolchains))
		for i, tc := range toolchains {
			names[i] = tc.Name
		}
		fmt.Printf("Wrote AGENTS.md (detected: %s)\n", strings.Join(names, ", "))
	}
	return 0
}

// toolchain is a detected project toolchain and the canonical commands an
// agent should run for it.
type toolchain struct {
	Name  string // human label, e.g. "Go"
	via   string // the file that proved its presence
	Build string
	Test  string
	Lint  string
}

// detectToolchains infers the project's toolchains from marker files at the
// repo root. Pure filesystem probing, so it is unit-testable in a temp dir.
func detectToolchains(root string) []toolchain {
	has := func(names ...string) string {
		for _, n := range names {
			if st, err := os.Stat(filepath.Join(root, n)); err == nil && !st.IsDir() {
				return n
			}
		}
		return ""
	}
	globHas := func(pattern string) string {
		matches, _ := filepath.Glob(filepath.Join(root, pattern))
		if len(matches) > 0 {
			return filepath.Base(matches[0])
		}
		return ""
	}

	var out []toolchain
	if via := has("go.mod"); via != "" {
		out = append(out, toolchain{"Go", via, "go build ./...", "go test ./...", "golangci-lint run"})
	}
	if via := has("package.json"); via != "" {
		out = append(out, toolchain{"TypeScript/Node", via, "npm run build", "npm test", "npm run lint"})
	}
	if via := has("Cargo.toml"); via != "" {
		out = append(out, toolchain{"Rust", via, "cargo build", "cargo test", "cargo clippy"})
	}
	if via := has("pyproject.toml", "requirements.txt"); via != "" {
		out = append(out, toolchain{"Python", via, "", "pytest", "ruff check ."})
	}
	if via := has("pom.xml"); via != "" {
		out = append(out, toolchain{"Java (Maven)", via, "mvn -q compile", "mvn test", ""})
	} else if via := has("build.gradle", "build.gradle.kts"); via != "" {
		out = append(out, toolchain{"Java (Gradle)", via, "./gradlew build", "./gradlew test", ""})
	}
	if via := has("CMakeLists.txt"); via != "" {
		out = append(out, toolchain{"C++ (CMake)", via, "cmake --build build", "ctest --test-dir build", ""})
	}
	if via := globHas("*.sln"); via != "" {
		out = append(out, toolchain{"C# (.NET)", via, "dotnet build", "dotnet test", ""})
	}
	return out
}

// renderAgentsMD produces the repo AGENTS.md: the build/test/lint contract an
// agent needs to work in this repository, plus a pointer to the karya task
// workflow whose specs and artifacts live in .karya/.
func renderAgentsMD(project string, tcs []toolchain) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# AGENTS.md — %s\n\n", project)
	b.WriteString("Guide for AI coding agents (and humans) working in this repository.\n")
	b.WriteString("Generated by `karya init`; keep the commands below truthful — agent\n")
	b.WriteString("quality is capped by context quality.\n\n")

	b.WriteString("## Commands\n\n")
	if len(tcs) == 0 {
		b.WriteString("No toolchain detected. Fill in:\n\n")
		b.WriteString("| Action | Command |\n|---|---|\n")
		b.WriteString("| Build | … |\n| Test | … |\n| Lint | … |\n")
	} else {
		b.WriteString("| Toolchain | Build | Test | Lint |\n|---|---|---|---|\n")
		for _, tc := range tcs {
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
				tc.Name, orDash(tc.Build), orDash(tc.Test), orDash(tc.Lint))
		}
	}

	b.WriteString("\n## Conventions\n\n" +
		"- Run the test suite before considering any change done; keep it green.\n" +
		"- Match the existing code style; prefer small, reviewable changes.\n\n" +
		"## karya task workflow\n\n" +
		"This repo is worked on through karya tasks: each task is a spec contract\n" +
		"(`.karya/tasks/<id>/SPEC.md`) executed in an isolated git worktree, with human\n" +
		"gates between plan, implementation, and verification. Only `SPEC.md` files are\n" +
		"meant to be committed from `.karya/`; everything else there is local runtime\n" +
		"state. See `karya help task` for the command surface.\n")
	return b.String()
}

// orDash renders an empty command cell as a dash.
func orDash(s string) string {
	if s == "" {
		return "—"
	}
	return "`" + s + "`"
}
