package lang

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// MiseVars are the karya-prefix paths embedded in the generated mise config so
// language runtimes keep their state inside karya's isolated tree rather than
// the user's home defaults.
type MiseVars struct {
	// GoPath is GOPATH for the Go toolchain (module cache, installed binaries).
	GoPath string
	// CargoHome is CARGO_HOME for the Rust toolchain.
	CargoHome string
}

// miseTool maps a catalog language to the mise tool key used in [tools].
// TypeScript shares the Node runtime; system languages (cpp) have no runtime.
func miseTool(lang string) string {
	for _, l := range Catalog {
		if l.Name == lang {
			if l.System {
				return ""
			}
			return l.MiseTool
		}
	}
	return ""
}

// GenerateMiseConfig renders an isolated mise config.toml from the selection.
// Multiple versions become a mise array; system languages are skipped. [env]
// pins JAVA_HOME (resolved from mise at eval time), GOPATH, and CARGO_HOME when
// the respective language is selected, keeping runtime state under the karya
// prefix. The output is deterministic for a given selection.
func GenerateMiseConfig(s *Selection, vars MiseVars) string {
	var b strings.Builder
	b.WriteString("# Generated by karya from languages.local — do not edit.\n")
	b.WriteString("# Re-run `karya lang` to change. Isolated: karya never touches your global mise.\n\n")
	b.WriteString("[tools]\n")

	hasJava, hasGo, hasRust := false, false, false
	for _, lang := range s.order {
		switch lang {
		case "java":
			hasJava = true
		case "go":
			hasGo = true
		case "rust":
			hasRust = true
		}
		tool := miseTool(lang)
		if tool == "" {
			continue // system toolchain (cpp) — no managed runtime
		}
		fmt.Fprintf(&b, "%s = [%s]\n", tool, quoteVersions(s.versions[lang]))
	}

	b.WriteString("\n[env]\n")
	if hasJava {
		// exec resolves the primary java version at env-evaluation time.
		b.WriteString("JAVA_HOME = { value = \"{{ exec(command='mise where java') }}\", tools = true }\n")
	}
	if hasGo {
		fmt.Fprintf(&b, "GOPATH = %q\n", vars.GoPath)
	}
	if hasRust {
		fmt.Fprintf(&b, "CARGO_HOME = %q\n", vars.CargoHome)
	}

	b.WriteString("\n[settings]\n")
	b.WriteString("experimental = true\n")
	return b.String()
}

// quoteVersions renders versions as a mise TOML array body: "3.14", "3.13".
func quoteVersions(versions []string) string {
	quoted := make([]string, len(versions))
	for i, v := range versions {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(quoted, ", ")
}

// WriteMiseConfig renders and writes the isolated mise config to path, creating
// the parent dir.
func WriteMiseConfig(path string, s *Selection, vars MiseVars) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("lang: create mise config dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(GenerateMiseConfig(s, vars)), 0o644); err != nil {
		return fmt.Errorf("lang: write mise config %s: %w", path, err)
	}
	return nil
}
