return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
      preset = "helix",
      delay = 0,
      icons = {
        mappings = false,
      },
      spec = {
        { "<leader>e", group = "Diagnostics/Errors" },
        { "<leader>E", desc = "Open oil (file dir)" },
        { "<leader>O", desc = "Open oil (cwd)" },
        { "<leader>f", group = "Files" },
        { "<leader>s", group = "Search" },
        { "<leader>g", group = "Git" },
        { "<leader>d", group = "Debug" },
        { "<leader>l", group = "LSP" },
        { "<leader>t", desc = "Terminal (tmux pane / float)" },
        { "<leader>q", group = "Session" },
        -- One context-aware "Code" group, identical across every language: the
        -- active buffer's language provides the actions under <leader>c. The
        -- per-key labels come from the buffer-local maps registered by
        -- util.langmaps, so only the group label is declared here.
        { "<leader>c", group = "Code" },
        { "<leader>cw", group = "Workspace (Java)" },
        -- Agent bridge: send editor context to the coding-agent pane.
        { "<leader>a", group = "Agent" },
        { "<leader>?", "<cmd>KaryaTutorial<cr>", desc = "Start the karya tutorial" },
        { "<leader>S", desc = "Save" },
        { "<leader>Z", desc = "Quit" },
        { "<leader>x", desc = "Close buffer" },
        { "<leader>:", desc = "Command history" },
        { "<leader><space>", desc = "Buffers" },
        { "<leader>st", desc = "Search TODOs" },
        { "<leader>ee", desc = "Diagnostics (Trouble)" },
        { "<leader>er", desc = "LSP references (Trouble)" },
        { "<leader>ei", desc = "LSP implementations (Trouble)" },
        { "<leader>en", desc = "Next trouble item" },
        { "<leader>ep", desc = "Previous trouble item" },
        { "<leader>gd", desc = "Diffview" },
        { "<leader>gh", desc = "Preview hunk" },
        { "<leader>gb", desc = "Line blame" },
        { "<leader>gs", desc = "Stage hunk", mode = { "n", "v" } },
        { "<leader>gr", desc = "Reset hunk", mode = { "n", "v" } },
        { "<leader>gu", desc = "Undo stage hunk" },
        { "<leader>gn", desc = "Next hunk" },
        { "<leader>gp", desc = "Previous hunk" },
        { "<leader>gD", desc = "Diff against index" },
        { "<leader>db", desc = "Toggle breakpoint" },
        { "<leader>dB", desc = "Conditional breakpoint" },
        { "<leader>dc", desc = "Continue" },
        { "<leader>di", desc = "Step into" },
        { "<leader>do", desc = "Step over" },
        { "<leader>dO", desc = "Step out" },
        { "<leader>dr", desc = "Open REPL" },
        { "<leader>du", desc = "Toggle UI" },
        { "<leader>dt", desc = "Terminate" },
        { "<leader>dx", desc = "Clear breakpoints" },
        { "gd", desc = "Definition" },
        { "gD", desc = "Declaration" },
        { "gr", desc = "References" },
        { "gi", desc = "Implementation" },
        { "gt", desc = "Type definition" },
        { "K", desc = "Hover documentation" },
        { "<C-k>", desc = "Signature help", mode = "i" },
        { "<leader>lr", desc = "Rename symbol" },
        { "<leader>la", desc = "Code action", mode = { "n", "v" } },
        { "<leader>lf", desc = "Format with LSP", mode = { "n", "v" } },
        { "<leader>ls", desc = "Workspace symbols" },
        { "<leader>ld", desc = "Document symbols" },
      },
    },
  },
}
