#!/usr/bin/env bash
# update-formula.sh — regenerate the cross-platform Homebrew formula for a release.
#
# karya's Homebrew tap lives in this repo at HomebrewFormula/karya.rb. A plain
# Homebrew formula (not a Cask) is used deliberately: it installs on **both**
# macOS and Linux Homebrew, and does not depend on GoReleaser's deprecated `brews`
# generator. This script fills in the version + per-platform SHA-256s from the
# release's checksums.txt (as produced by GoReleaser) so `brew install karya`
# fetches the right prebuilt tarball for the user's OS/arch.
#
# Usage: scripts/update-formula.sh <tag> <checksums.txt>
#   e.g. scripts/update-formula.sh v0.1.0 dist/checksums.txt
set -euo pipefail

tag="${1:?usage: update-formula.sh <tag> <checksums.txt>}"
sums="${2:?usage: update-formula.sh <tag> <checksums.txt>}"
version="${tag#v}"
repo="drjzlyan/karya"
base="https://github.com/$repo/releases/download/$tag"

[[ -f "$sums" ]] || { echo "update-formula: no checksums file at '$sums'" >&2; exit 1; }

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$repo_root/HomebrewFormula/karya.rb"

# sha <os> <arch> — the SHA-256 of the karya tarball for that platform.
sha() {
	local file="karya_${version}_$1_$2.tar.gz"
	local s
	s="$(awk -v f="$file" '$2 == f { print $1 }' "$sums")"
	[[ -n "$s" ]] || { echo "update-formula: no checksum for $file in $sums" >&2; exit 1; }
	printf '%s' "$s"
}

mkdir -p "$repo_root/HomebrewFormula"
cat >"$out" <<EOF
# Generated by scripts/update-formula.sh on release — do not edit by hand.
class Karya < Formula
  desc "AI-first, terminal-based IDE shipped as a single Go binary"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/karya_${version}_darwin_arm64.tar.gz"
      sha256 "$(sha darwin arm64)"
    end
    on_intel do
      url "$base/karya_${version}_darwin_amd64.tar.gz"
      sha256 "$(sha darwin amd64)"
    end
  end

  on_linux do
    on_arm do
      url "$base/karya_${version}_linux_arm64.tar.gz"
      sha256 "$(sha linux arm64)"
    end
    on_intel do
      url "$base/karya_${version}_linux_amd64.tar.gz"
      sha256 "$(sha linux amd64)"
    end
  end

  def install
    bin.install "karya"
  end

  test do
    system "#{bin}/karya", "--version"
  end
end
EOF

echo "update-formula: wrote $out for $tag"
